name: stuff
description: "Things"
author: "Me"
inputs:
  tags:
    description: "Tested"
    required: false
outputs: {}
 
runs:
  using: composite
  steps: 
    - name: Mm
      uses: actions/checkout@v2
      with:
        repository: Bigmotech/TestingActions
      
    - name: Do thing
      uses: Bigmotech/TestingActions/.github/workflows/blank.yml@main
      
