name: stuff
description: "Things"
author: "Me"
inputs:
  tags:
    description: "Tested"
    required: false
outputs: {}
 
runs:
  using: composite
  steps: 
    - name: Mm
      uses: actions/checkout@v2
      with:
        repository: Bigmotech/TestingActions
        
    - name: hello
      uses: ./.github.workflows/blank.yml
      
    - name: Do thing
      run: |
            echo ${{ github.repository}}
            echo ${{ github.workspace }}
            echo $GITHUB_ENV.TEST
      shell: bash
      
