name: stuff
description: "Things"
author: "Me"
inputs:
  tags:
    description: "Tested"
    required: false
outputs: {}
 
runs:
  using: composite
  steps: 
    - name: Mm
      uses: actions/checkout@v2
      
    - name: Do thing
      run: |
            echo ${{ github.repository}}
            echo ${{ env.TESTINGEM}}
            echo hello
      shell: bash
